### ISSUE TITLE
[2장] typeof, instance of, 타입 단언에 대해서 설명해주세요.

### ISSUE THREAD

**Issue by hyejj19** [Woowahan-TS/woowahan-ts#10]
📝 p.62

🧐 typeof, instance of, 타입 단언에 대해서 설명해주세요.

**Comment by jinsupark4255** [comment]
- typeof 연산자는 변수의 데이터 타입을 문자열로 변환합니다. 주로 원시 타입을 체크할 때 활용합니다.
다만, null인 경우에는 Object라는 오류를 발생시키기 때문에 (JavaScript의 언어적 오류)
   ```tsx
   if(yourVariable != null && typeof yourVariable === 'object')
   ```
   이런식으로 처리를 해줘야 합니다.

- instance of 연산자는 주어진 객체가 특정 클래스의 인스턴스인지, 혹은 특정 프로토타입을 상속 받고 있는지 확인합니다.
   ```tsx
   var Person = function(){
      this.name = "unikys";
   };
   var inst = new Person();

   inst instanceof Person; // === true
   inst instanceof Object; // === true
   typeof inst; // === 'object'
   ```
   
- 타입 단언은 타입을 강제할 수 있는 as 키워드를 사용하는 것이다. 하지만 타입 단언은 컴파일러에게 개발자가 타입을 단언했기에 에러를 띄우지 말라고 알려줌으로써 런타임에서 에러가 발생하는 문제를 야기할 수 있다. -> 타입스크립트를 사용하는 이유가 없어짐
   ```tsx
   interface human {
	   sayhi: string;
  	   age: number;
   }

   let person = {
	   // 아무것도 안 넣음
   } as human;

   console.log(person.sayhi)
   ```

**Comment by YunjiNam** [comment]
typeof 는 연산하기 전에 피연산자의 데이터 타입을 나타내는 문자열을 반환합니다.

Instance of 는 프로토타입 체이닝에 생성자의 프로토타입 속성이 존재하는지 확인할 수 있습니다.  typeof 연산자처럼 instanceof 연산자의 필터링으로 타입이 보장된 상태에서 값을 사용할 수 있습니다.

타입단언은  as 키워드를 사용해 타입을 강제하는 문법입니다.
