### ISSUE TITLE
[3장] 제네릭이란 무엇이고 왜, 언제 사용하나요?

### ISSUE THREAD

**Issue by hyejj19** [Woowahan-TS/woowahan-ts#14]
📝 p.106, 116

🧐 제네릭 타입이란 무엇이고, 왜, 언제, 무슨 이유로 사용하나요?

**Comment by jinsupark4255** [comment]
- 제네릭은 함수, 인터페이스, 클래스 등을 정의할 때 구체적인 타입을 지정하는 대신, 타입을 파라미터로 받아서 사용하는 방법이다.

- 제네릭은 같은 로직을 다양한 타입에 대해 사용할 수 있게 되어 코드의 재사용성이 증가하기 때문에 사용한다.

- 사용 이유 1: 여러 타입을 하나의 함수나 클래스에서 처리해야 할 때
  - 예를 들어, 배열의 모든 요소를 출력하는 함수를 만들 때, 모든 타입의 배열을 처리할 수 있도록 제네릭을 사용할 수 있다.
- 사용 이유 2:  API의 사용자가 어떤 타입을 사용할지 모를 때
  - 제네릭을 통해 유연하게 타입을 정의할 수 있다.

**Comment by 0xEF6AE** [comment]
1. 제네릭은 타입을 마치 함수의 매개변수처럼 사용할 수 있게 해주는 기능입니다. 즉, 여러 타입에 대해 재사용 가능한 컴포넌트를 만들 수 있게 해줍니다.

2. 사용 이유
타입 안전성: 컴파일 시점에 타입을 체크할 수 있어 런타임 오류를 줄일 수 있습니다.
코드 재사용: 다양한 타입에 대해 동작하는 함수나 클래스를 작성할 수 있습니다.
타입 추론: TypeScript가 타입을 추론할 수 있게 해줍니다.

3. 사용 시기
여러 타입에 대해 동작하는 함수나 클래스를 만들 때 사용합니다.
타입 간의 관계를 표현해야 할 때 사용합니다.
컬렉션(배열, 맵 등)을 다룰 때 사용합니다.
