### ISSUE TITLE
[3장] 제네릭 에러 상황을 보고 에러가 발생하는 이유를 설명해주세요 (1)

### ISSUE THREAD

**Issue by jinsupark4255** [Woowahan-TS/woowahan-ts#15]
📝 p.108

🧐 제네릭은 일반화된 데이터 타입을 의미합니다. 다음 코드를 보고 왜 에러가 발생하는지 설명해주세요.
```tsx
function example<T>(arg: T): number {
   return arg.length; // 에러 발생
}
```

**Comment by 0xEF6AE** [comment]
1. 제네릭 타입 T는 어떤 타입이든 될 수 있습니다. 예를 들어, number, boolean, 사용자 정의 객체 등이 될 수 있습니다.

2. 하지만 함수 내에서 arg.length를 호출하고 있습니다. length 속성은 모든 타입에 존재하지 않습니다. 예를 들어, number 타입이나 boolean 타입에는 length 속성이 없습니다.
 
3.TypeScript는 컴파일 시점에 이런 잠재적인 오류를 감지하고 경고합니다. 즉, T 타입의 모든 가능한 값에 대해 length 속성의 존재를 보장할 수 없기 때문에 에러가 발생합니다.

**Comment by hyejj19** [comment]
현 시점에서 arg 의 타입을 정확히 알 수 없기 때문입니다. 따라서 arg 의 속성에 length 가 존재하는지 여부를 판단할 수 없기 때문에 에러가 발생하고, 이를 방지하기 위해선 T 제네릭 타입이 length 속성을 가진 제네릭 타입이어야 한다고 강제해주어야 합니다.
```ts
function example<T extends { length: number }>(arg: T): number {
    return arg.length;
}
```
