### ISSUE TITLE
[3장] 제네릭 에러 상황을 보고 에러가 발생하는 이유를 설명해주세요 (2) 

### ISSUE THREAD

**Issue by jinsupark4255** [Woowahan-TS/woowahan-ts#16]
📝 p.109

🧐 제너릭을 tsx 확장자 파일에서 사용할 때 조심해야 될 부분이 있습니다. 다음 코드를 보고 왜 에러가 나는지, 그에 따라 tsx 파일에서 제네릭을 사용할 때 어떤 부분을 조심해야 하는지 설명해주세요.

```tsx
const arrowExampleFunc = <T>(arg: T): T[] => {
   return new Array(3).fill(arg);
};
```

**Comment by 0xEF6AE** [comment]
1. 코드가 에러가 나는 이유 : TSX(TypeScript JSX) 파일에서 <T>는 제네릭 타입 매개변수가 아니라 JSX 태그로 해석됩니다.

2. 조심해야 할 부분 : 화살표 함수에서 제네릭 사용: <T extends {}>, <T,>, 또는 as const를 사용하여 제네릭임을 명시적으로 표시해야 합니다.

**Comment by hyejj19** [comment]
파일 확장자가 tsx 일 경우 컴파일러가 <> 꺽쇠 표시를 jsx(tsx) 문법으로 잘못 해석하여 에러가 발생하게 됩니다. 따라서 이 타입이 제네릭 타입임을 명시하기 위해 extends 키워드 등을 사용해 컴파일러에게 명확히 알려주어야 합니다.

**Comment by jinsupark4255** [comment]
오류가 발생하는 이유는, 화살표 함수에서 제네릭을 사용할 때 컴파일러는 이게 제네릭인지 태그인지 구별하는데에 착각할 여지가 있다.
