### ISSUE TITLE
[2장] 덕 타이핑과 구조적 타이핑의 차이를 설명해주세요.

### ISSUE THREAD

**Issue by jinsupark4255** [Woowahan-TS/woowahan-ts#2]
📝 p.47

🧐 자바스크립트의 덕 타이핑과 타입스크립트의 구조적 타이핑은 서로 구분되는 타이핑 방식입니다. 두 방식의 특징과 차이를 설명해주세요.

**Comment by YunjiNam** [comment]
덕 타이핑은 어떤 함수의 매개변숫값이 올바르게 주어진다면 그 값이 어떻게 만들어졌는지 신

**Comment by YunjiNam** [comment]
덕 타이핑은 어떤 타입에 부합하는 변수와 메서드를 가질 경우 해당 타입에 속하는 것으로 간주하는 방식이다.
구조적 타이핑은 명시적인 이름을 가지고 타입을 구분하는 대신 객체나 함수가 가진 구조적 특징을 기반으로 타이핑하는 방식이다. 구조적 타이핑은 객체 간 속성이 동일하다면 서로 호환된다.
두 타입 모두 객체가 가진 속성을 기반으로 타입을 검사한다는 공통점이 있지만 타입을 검사하는 시점에 차이가 있다.
덕 타이핑은 런타임에 타입을 검사하고 구조적 타이핑은 컴파일타임에 타입체커가 타입을 검사한다.

**Comment by hyejj19** [comment]
덕 타이핑이란 별개의 두 객체가 서로 같은 변수와 메서드를 가진다면 두 객체는 동일한 타입으로 간주하는 것입니다. 
(예를 들어 어떤 새가 오리와 같은 속성을 가진다면 그 새를 오리로 본다는 의미에서 duck typing 이라는 이름이 붙었습니다.) 

타입스크립트는 자바스크립트의 확장성 성격을 가졌기 때문에 이러한 구조적 특징을 기반으로 타이핑을 합니다. 차이점은 덕 타이핑의 경우 런타임에 타입을 검사하고, 구조적 타이핑은 컴파일 타임에 타입을 검사하기 때문에 타입 안정성 측면에서 차이가 있습니다.
