### ISSUE TITLE
[4장] 유니온 타입에서 식별자의 역할은 무엇인가요?

### ISSUE THREAD

**Issue by jinsupark4255** [Woowahan-TS/woowahan-ts#24]
📝 p.140 ~ 143

🧐 타입을 식별자 없이 유니온으로 묶으면 타입스크립트에서 느슨한 타입 검사를 컴파일 단계에서 진행합니다. 주어진 문제에서 타입 에러를 뱉지 않는 이유에 대해 설명해주시고, 이를 막기 위해 사용하는 식별자가 어떻게 이 문제를 해결하는지 설명해주세요.

- 문제 상황
```tsx
type TextError = {
   errorCode: string;
   errorMessage: string;
};

type ToastError = {
   errorCode: string;
   errorMessage: string;
   toastShowDuration: number;
};

type AlertError = {
   errorCode: string;
   errorMessage: string;
   onConfirm: () => void;
};

type ErrorFeedbackType = TextError | ToastError | AlertError;

const errorArr: ErrorFeddbackType[] = [
   {
      errorCode: "999",
      errorMessage: "잘못된 에러",
      toastShowDuration: 3000,
      onConfirm: () => {},
   },
];
```

**Comment by YunjiNam** [comment]
유니온 타입에서는 해당 타입의 속성들 중 일부를 포함하고 있으면 타입 검사가 통과될 수 있기 때문에 타입에러가 발생하지 않습니다.
이러한 문제를 막기 위해 각 타입이 비슷한 구조를 가지지만 호환되지 않도록 만들어 주는 `식별할 수 있는 유니온`을 사용할 수 있습니다.
구조 호환을 막기 위해 타입마다 구분할 수 있는 판별자를 달아주어 포함 관계를 제거할 수 있습니다.

**Comment by 0xEF6AE** [comment]
타입 에러가 발생하지 않는 이유: TypeScript는 유니온 타입의 경우, 객체 리터럴에 유니온의 모든 타입에 존재하는 속성과 일부 타입에만 존재하는 속성이 모두 포함되어 있다면 이를 유효한 것으로 간주합니다.

식별자를 사용한 문제 해결: 이 문제를 해결하기 위해 "식별 유니온(discriminated union)" 패턴을 사용할 수 있습니다. 각 타입에 고유한 식별자(discriminator)를 추가하여 TypeScript가 정확히 어떤 타입인지 구분할 수 있게 합니다.

**Comment by hyejj19** [comment]
유니온 타입에서는 유니온 타입을 이루는 타입들이 비슷한 구조를 가지고 있다면 각 타입에 대해 엄격한 타입 검사를 수행하지 않습니다. 그러나 식별자 역할을 하는 유닛 값이 존재한다면 해당 식별자를 기준으로 유니온 타입의 세부 타입을 더 정확하게 식별 가능해집니다.
