### ISSUE TITLE
[4장] instanceof 와 in 에 대해서 설명해주세요

### ISSUE THREAD

**Issue by YunjiNam** [Woowahan-TS/woowahan-ts#26]
📝 p.134

🧐 타입 가드를 하는 방법 중 객체의 타입을 추론하는 방법인 instanceof 와 in 은 비슷해 보이지만 다른 용도로 사용되는데요. instanceof 와 in 에 대해 설명해주세요.

**Comment by jinsupark4255** [comment]
instanceof는 주어진 객체가 특정 클래스의 인스턴스인지 확인하는 특징이 있습니다. 따라서 interface나 type에서는 사용하기 어려운 특징이 있다고 말씀드릴 수 있습니다.

다만, in 연산자는 객체의 속성 존재 유무를 판별하는데에 사용되는 특징이 있습니다. interface나 type에서 사용할 수 있는 특징을 가지고 있어서 컴파일 단계에서 타입스크립트가 객체 타입에 속성이 존재하는지 검사할 수 있어서 타입 가드(컴파일 단계)에 용이합니다.

**Comment by hyejj19** [comment]
instance of 는 런타임에서 값으로 평가되는 개념 (클래스, 객체) 의 인스턴스인지를 확인하는 개념입니다.
in 연산자는 객체에 특정한 속성이 존재하는지 여부를 확인하는 연산자입니다. 그래서 그 속성의 값에 상관 없이 존재 여부만 판단한다는 특징이 있습니다. 

```ts
interface A {
  age: number;
  name: string;
}

if ('age' in A) {
  console.log('아하');
}  // 'A' only refers to a type, but is being used as a value here.
```
위와 같이 직접 참조는 여전히 안되네요.. ;ㅅ;
예시에서는 매개변수에 타입을 선언하고 해당 매개변수 객체에서 특정 속성의 존재 여부를 판단하는데 사용됩니다.
그래서 instance of 에 비해 조금 더 좁은 영역에서 검사를 할 때 활용된다고 볼 수도 있을 것 같습니당.
