### ISSUE TITLE
[2장] 타입스크립트의 컴파일 방식에 대해 설명해주세요.

### ISSUE THREAD

**Issue by YunjiNam** [Woowahan-TS/woowahan-ts#3]
📝 p.41

❓ 타입스크립트는 다른 언어와는 다른 컴파일 방식을 가지고 있습니다. 타입스크립트의 컴파일 방식과 그러한 컴파일 방식을 사용하는 이유에 대해 설명해주세요.

**Comment by jinsupark4255** [comment]
- 타입스크립트를 컴파일하면 타입이 모두 제거된 자바스크립트 소스코드만 남게 된다. 이는 타입스크립트가 자바스크립트에 타입이라는 레이어를 얹은 확장 언어이기 때문이다.

**Comment by hyejj19** [comment]
타입스크립트는 다른 컴파일 언어와 달리, 컴파일 결과물이 바이너리 코드가 아닌 자바스크립트 소스코드로 변환됩니다. 
1. 타입스크립트는 약타입 언어인 자바스크립트의 런타임 안정성을 보강하기 위해 등장한 언어입니다.
2. 런타임 환경은 자바스크립트 소스코드를 컴파일 하여 실행되도록 설계되어 있습니다.
3. 이와 같이 자바스크립트의 확장, 슈퍼셋과 같은 성격을 지니고 있으면서 보강의 역할을 하기 때문에, '트랜스파일' 이라는 용어를 사용하기도 합니다.
