### ISSUE TITLE
[4장] 타입스크립트의 유니온 타입과 교차타입에 대해 설명해주세요

### ISSUE THREAD

**Issue by hyejj19** [Woowahan-TS/woowahan-ts#30]
📝 125p.
🧐 타입스크립트의 유니온 타입과 교차타입에 대해 설명해주세요

( 유니온 타입이란 | 연산자를 사용, 합집합의 개념. 합집합이라고 해서 A 와 B 타입의 모든 속성이 합쳐지는게 아니라, 그냥 그 타입이 A 이거나 B 인거임.

교차 타입은 & 연산자를 사용해 만들어낼 수 있으며 집합의 개념으로 따지면 합집합. 교차타입의 핵심은 교차타입 C 가 A & B  일 때, 타입 C 는 A 와 B 를 모두 만족 시킬 수 있느냐 없느냐를 판단하여 결정된다.

만약 A와 B 중 아무것도 겹치는 것이 없으면 never 공집합이 되는 것.)

**Comment by jinsupark4255** [comment]
유니온 타입은 쉽게 말해 여러개의 타입 중 하나를 만족하면 성립하는 타입입니다.
예를 들어 A타입과 B타입이 유니온 타입으로 묶이고 props가 이에 해당하는 타입을 받게 될때, (props: A | B) props는 무조건 A 또는  B를 만족하는 타입이 들어와야 합니다.

교차 타입은 합집합으로 설명하면 좋을 것 같습니다.
예를 들어 A타입과 B타입이 교차 타입으로 묶이면 A와 B 타입의 속성을 모두 가지고 있는 새로운 C타입이 완성되는 식입니다.
(props: A&B) props는 A와 B의 속성을 모두 가지고 있는 props이어야 합니다.
