### ISSUE TITLE
[5장] PickOne 커스텀 유틸리티 타입

### ISSUE THREAD

**Issue by jinsupark4255** [Woowahan-TS/woowahan-ts#32]
📝 p.168 - 171

🧐 PickOne 커스텀 유틸리티 타입으로 원하고자 하는 속성만 받도록 구현할 수 있습니다. 코드가 정확히 어떻게 동작하는지 대략적으로 설명해주세요.

```tsx
type PickOne<T> = {
   [P in keyof T]: Record<P, T[P]> & Partial<Record<Exclude<keyof T, P>, undefined>>;
}[keyof T];

type Card = {
   card: string
};
type Account = {
   account: string
};
type CardOrAccount = PickOne<Card & Account>;
function withdraw (type: CardOrAccount) {
   ...
}

withdraw({ card: "hyundai", account: "hana" }); // 에러 발생
```

**Comment by 0xEF6AE** [comment]
- [P in keyof T]: T의 모든 키에 대해 반복합니다.
- Record<P, T[P]>: 현재 키 P와 그 값의 타입 T[P]로 이루어진 레코드를 생성합니다.
- Partial<Record<Exclude<keyof T, P>, undefined>>: 현재 키 P를 제외한 모든 키를 undefined로 설정할 수 있는 부분적(Partial) 레코드를 생성합니다.
- 이 두 레코드를 &(intersection)로 결합합니다.
- 마지막으로 [keyof T]를 통해 생성된 유니온 타입 중 하나를 선택합니다.

이 타입은 T의 모든 키 중 정확히 하나만 필수로 선택하고, 나머지는 모두 undefined로 설정할 수 있는 타입을 생성합니다.

type Card = { card: string };
type Account = { account: string };
type CardOrAccount = PickOne<Card & Account>;
CardOrAccount는 다음 두 타입의 유니온이 됩니다:

{ card: string; account?: undefined }
{ account: string; card?: undefined }

이 호출에서 에러가 발생하는 이유는 CardOrAccount 타입이 card와 account 중 정확히 하나만 제공되어야 하는데, 두 속성 모두 제공되었기 때문입니다.

**Comment by hyejj19** [comment]
- PickOne 유틸리티 타입은 하나의 값 만을 필수로 하고 나머지 모든 값을 undefined 로 초기화 합니다.
- PickOne 유틸리티 타입은 객체 타입의 제네릭 T의 모든 키와 value 를 포함한 Record 타입과 Partial 타입의 교차타입으로 구성되어있습니다. 
- Partial 은 해당하는 모든 속성을 옵셔널로 만들어주는 유틸타입 입니다.
- Exclude 는 현재 key에 해당하는 value 를 T 타입에서 제외합니다. 제외된 나머지를 키로, 그 값을 undefinded 로 초기화하는 Record 를 만들고 이 Record 를 다시 Partial 로 전달해 나머지 키값에 대한 옵셔널 필드를 가지도록 생성합니다.
- & 연산자로 이 두 타입을 묶어 타입이 해당할 수 있는 모든 경우를 합치고, 다시 맵드 타입으로 재탄생시킵니다.
