### ISSUE TITLE
[6장] tsc와 Babel의 공통점과 차이점을 설명해주세요.

### ISSUE THREAD

**Issue by 0xEF6AE** [Woowahan-TS/woowahan-ts#38]
📝 p191
🧐 tsc라고 불리는 타입스크립트 컴파일러는 자바스크립트 컴파일러 Babel과 유사하다고도 볼 수 있지만 명확한 차이점을 가집니다.
tsc와 Babel의 공통점과 차이점에 대해서 설명해주세요.

**Comment by jinsupark4255** [comment]
공통점: tsc와 바벨 모두 소스코드를 ES5 이하의 자바스크립트 코드로 컴파일합니다.
차이점: 바벨은 tsc와는 다르게 타입 검사를 진행하지 않습니다.

**Comment by YunjiNam** [comment]
공통점은 tsc 와 바벨이 소스코드를 ES5 이하 자바스크립트 코드로 컴파일해 준다는 것입니다.
차이점은 바벨은 tsc 처럼 타입 검사를 하지 않는다는 것입니다.

**Comment by hyejj19** [comment]
공통점 : 소스코드의 트랜스파일링 (특정 타겟 버전의 js 로 변환)
차이점 : 타입 체킹은 tsc 의 고유 기능!
