### ISSUE TITLE
[6장] 타입스크립트 소스코드가 실행되는 과정에 대해서 설명해주세요.

### ISSUE THREAD

**Issue by hyejj19** [Woowahan-TS/woowahan-ts#40]
📝 184p

🧐 타입스크립트 소스코드가 실행되는 과정에 대해서 설명해주세요. (컴파일타임, 런타임을 중심으로 전반적인 과정)

**Comment by jinsupark4255** [comment]
### 컴파일 타임
- 타입스크립트 컴파일러는 소스 코드를 분석하면서 타입이 일관성 있고 올바르게 사용되었는지 체크합니다.
- 타입스크립트 코드는 tsc 컴파일러를 통해 ECMAScript 버전의 자바스크립트 코드로 변환됩니다.

### 런타임
- 자바스크립트 소스코드를 자바스크립트 AST로 만듭니다.
- AST가 바이트 코드로 변환됩니다.
- 런타임에서 바이트 코드가 평가되어 프로그램이 종료됩니다.

**Comment by YunjiNam** [comment]
타입스크립트 컴파일러는 컴파일 타임에 타입스크립트 소스코드를 타입스크립트 AST 로 만들어 타입을 검사하고 AST 를 자바스크립트 소스로 변환합니다.
그리고 런타임에 변환된 자바스크립트 소스코드로 AST 를 생성하고 생성된 AST 가 바이트 코드로 변환되어 런타임에서 평가되어 실행됩니다.

**Comment by 0xEF6AE** [comment]
컴파일 타임
- 타입 체킹: TypeScript 컴파일러(tsc)가 소스 코드를 분석하여 타입 오류를 검사합니다.
변수, 함수, 클래스 등의 타입을 확인하고 타입 불일치나 오류를 찾아냅니다.

- 트랜스파일링: TypeScript 코드를 JavaScript 코드로 변환합니다.
이 과정에서 타입 정보와 TypeScript 전용 문법이 제거됩니다.
타겟 JavaScript 버전(ES5, ES6 등)에 맞게 코드를 변환합니다.

런타임
- 코드 로딩: 브라우저나 Node.js 환경에서 JavaScript 코드를 로드합니다.
- 파싱: JavaScript 엔진이 코드를 파싱하여 Abstract Syntax Tree(AST)를 생성합니다.  생성된 AST 가 바이트 코드로 변환되어 런타임에서 평가되어 실행됩니다. 이 시점에서 타입 정보는 이미 제거되었으므로, 순수한 JavaScript로 동작합니다.
