### ISSUE TITLE
[6장] 컴파일러의 역할에 대해 설명해주세요

### ISSUE THREAD

**Issue by jinsupark4255** [Woowahan-TS/woowahan-ts#41]
📝 p.191

🧐 타입스크립트 컴파일러의 역할은 크게 2가지로 나뉩니다. 이에 대해 자세히 설명해주세요.

**Comment by YunjiNam** [comment]
타입스크립트 컴파일러는 `코드 검사기` 와 `코드 변환기` 이렇게 두 가지의 역할로 동작합니다.
코드 검사기로서의 타입스크립트 컴파일러는 정적으로 코드를 분석해 에러를 검출하며, 코드를 실행하기 전에 런타임에서 발생할 수 있는 문법 오류, 타입 에러를 사전에 알려줍니다.
코드 변환기로서의 타입스크립트 컴파일러는 타입을 검사한 후 런타임 환경에서 동작할 수 있게 자바스크립트로 변환합니다.

**Comment by hyejj19** [comment]
1. 개발자가 작성한 타입 정보를 가지고 타입 체킹을 진행, 런타임 이전에 타입에 관한 오류를 검출
2. 브라우저에서 동작할 수 있는 자바스크립트 소스코드로의 변환
