### ISSUE TITLE
[6장] AST 에 대해서 설명해주세요

### ISSUE THREAD

**Issue by YunjiNam** [Woowahan-TS/woowahan-ts#43]
📝 p.186

🧐 타입스크립트 컴파일러는 소스코드를 해석해서 AST 로 만드는 과정을 진행하는데요. AST에 대해 설명해주세요.

**Comment by hyejj19** [comment]
- AST 는 Abstract Syntax Tree 의 약자로, 추상 구문 트리 라고도 번역됨
- 컴파일 단계에서 의미 있는 단위(토큰) 으로 쪼개진 정보를 추상화하여 트리 형태로 만든 데이터
- 해당 정보를 토대로 코드 분석, 변환 등 다양하게 활용될 수 있고 이를 활용하는 대표적인 예시로 타입스크립트 컴파일러, eslint, prettier 같은 코드 포맷터 등이 있다.
