### ISSUE TITLE
[7장] API 모킹에 대해서 설명해주세요.

### ISSUE THREAD

**Issue by 0xEF6AE** [Woowahan-TS/woowahan-ts#44]
📝 239p

🧐 문제 내용
API 모킹에 대해서 설명해주세요.

**Comment by jinsupark4255** [comment]
- API 모킹은 백엔드 서버가 준비가 안되었을 때 사용하는 방법입니다.
- 실제 서버를 구축하고 운영할 필요 없이, 가상의 API를 통해 개발과 테스트를 진행할 수 있고 그에 따라 백엔드 api가 완료될 때까지 기다릴 필요가 없어집니다.
