### ISSUE TITLE
[8장] 공변성과 반공변성

### ISSUE THREAD

**Issue by jinsupark4255** [Woowahan-TS/woowahan-ts#55]
📝 p.279 - p.280

🧐 공변성과 반공변성의 의미를 설명해주시고, 일반 타입과 제네릭 타입이 가지고 있는 차이를 '공변성, 반공변성'을 활용하여 설명해주세요.

**Comment by jinsupark4255** [comment]
## 공변성과 반공변성의 의미
### 공변성
- 공변성은 하위 타입의 관계가 유지되는 방식을 의미한다. 타입 A가 타입 B의 하위 타입일 때, Container&lt;A&gt;가 Container&lt;B&gt;의 하위 타입이 되는 상황을 말한다.

### 반공변성
- 반공변성은 타입 관계가 역전되는 것을 의미한다. 타입 A가 타입 B의 하위 타입일 때, Container&lt;B&gt;가 Container&lt;A&gt;의 하위 타입이 되는 경우이다.

## 일반 타입과 제네릭 타입의 차이
- 일반 타입은 공변성을 띠고 있지만 제네릭 타입은 반공변성을 띠고 있다.

- 일반 타입 코드 예시
```tsx
interface User {
   id: string;
}

interface Member extends User {
   nickName: string;
}

let users: Array<User> = [];
let members: Array<Member> = [];

users = members; // 정상 작동
members = uses; // 에러
```

- 제네릭 타입 코드 예시
```tsx
type PrintUserInfo<U extends User> = (user: U) => void;

let printUser: PrintUserInfo<User> = (user) => console.log(user.id);

let printMember: PrintUserInfo<Member> = (user) => console.log(user.id, user.nickName);

printMember = printUser; // 정상 작동
printUser = printMember; // 에러
```

**Comment by YunjiNam** [comment]
공변성이란 타입 계층의 방향을 그대로 유지하는 성질로 좁은 타입으로 선언한 변수에 넓은 타입으로 선언한 변수가 할당 가능한 것을 말한다.
반공변성은  타입 계층의 방향이 반대로 적용되는 성질로 넓은 타입으로 선언한 변수에 좁은 타입으로 선언한 변수가 할당 가능한 것을 말한다.
아직 정확하게 이해하지 못해서 답변을 여기까지만 적어봤습니다ㅜㅜ
첨부한 참고문서 보면서 이해하려고 노력중입니다...
[참고문서](https://inpa.tistory.com/entry/TS-%F0%9F%93%98-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-%EA%B3%B5%EB%B3%80%EC%84%B1-%EB%B0%98%EA%B3%B5%EB%B3%80%EC%84%B1-%F0%9F%92%A1-%ED%95%B5%EC%8B%AC-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0)
