### ISSUE TITLE
[2장] TypeScript에서 interface와 type의 차이점과 각각의 사용 사례를 설명해주세요.

### ISSUE THREAD

**Issue by 0xEF6AE** [Woowahan-TS/woowahan-ts#6]
❓ TypeScript에서 interface와 type의 차이점과 각각의 사용 사례를 설명해주세요.

**Comment by jinsupark4255** [comment]
- interface는 type과는 달리 선언적 확장이 가능하다. (한번 선언한 interface를 다시 선언함으로써 확장하는 방법)
- interface는 객체 타입 선언에 사용되는 것이 일반적이고 type은 원시 타입 선언에 사용되는 것이 일반적이다.

**Comment by hyejj19** [comment]
interface 는 객체의 구조를 정의하고, type 은 타입의 별칭을 정의하는 역할을 합니다.
그렇기에 interface 는 extends(확장), implements(조합) 과 같은 키워드를 사용해 객체 타입의 확장 및 재사용성을 향상하는 목적으로도 활용 가능합니다. type 의 경우 computed value(계산된 값)을 활용하는 것이 가능하기 때문에 키 값 등 동적으로 계산하여 타입을 정의해야 하는 상황에 유용하게 활용할 수 있습니다.

**Comment by YunjiNam** [comment]
Interface 는 주로 객체의 타입을 정의할 때 사용됩니다. 인터페이스 간에 상속이 가능하며 extends 로 두 인터페이를 결합할 수 있습니다. 동일한 이름으로 타입 선언이 가능합니다.

Type 은 타입 별칭을 정의하는 데 사용됩니다. 객체 타입, 유니언 타입 등을 정의할 수 있습니다. Interface 와 다
르게 & 연산자로 다른 두 타입을 결합할 수 있습니다. 동일한 이름으로 선언이 불가능합니다.
