### ISSUE TITLE
[9장] MutableObject 와 RefObject 의 차이점을 설명해주세요

### ISSUE THREAD

**Issue by YunjiNam** [Woowahan-TS/woowahan-ts#60]
📝 p.295

🧐 useRef 는 MutableObject 또는 RefObject 를 반환하는데요. 이 둘의 차이점을 설명해주세요.

**Comment by hyejj19** [comment]
Mutable 이란 이름 그대로 속성을 변경할 수 있는 타입, Ref 는 readonly 타입입니다.
여기서 변경 가능, readonly 의 기준은 Ref 의 current 프로퍼티입니다. 
일반적으로 제네릭에 어떤 타입을 전달하느냐, 초기값으로 어떤 값을 전달하느냐에 따라 ref 의 반환 타입이 결정되는데
HtmlInputElement 와 같이 리액트 element 타입을 제네릭으로 전달하면 current 속성이 불변한 RefObject 타입이 반환됩니다.
current 속성을 개발자가 직접 제어할 것인지 아니면 리액트의 ref 속성으로 전달하여 리액트에서 관리하게 할 것인지에 따라 적절하게 선택하여 사용할 수 있습니다.
