### ISSUE TITLE
[2장] enum과 const enum, as const에 대해 설명해주세요.

### ISSUE THREAD

**Issue by jinsupark4255** [Woowahan-TS/woowahan-ts#7]
📝 p.61

❓ 프로젝트에서 상수관리를 할 때 enum, const enum, as const를 선택하여 사용합니다. 각 방법에 대해 설명해주시고 본인이 생각하기에 베스트 방법은 무엇인지, 그 이유도 설명해주세요.

**Comment by hyejj19** [comment]
- enum 은 값으로 존재하며 컴파일 이후에 런타임에 남아 사라지지 않습니다. 
- const enum 은 이와 달리 트리쉐이킹이 되기 때문에 번들 사이즈 최적화 측면에서 유리하다는 특징이 있습니다. 하지만 자료가 인라인으로 변환되기 때문에 컴파일 이후 디버깅이 어려워진다는 단점이 있습니다.
- enum의 경우 값으로 존재하기 때문에 메모리 오버헤드(자료에 접근하기 위한 추가 시간)가 있으나, 계산된 값을 사용할 수 있고 이터러블로 순회가 가능하다는 특징이 있습니다. 
- as const 는 객체의 불변성을 보장하고자 하고, 타입을 좁혀 추론 또한 가능하게 하는 키워드 입니다. 
- 양방향 맵핑의 기능을 적극 활용하는게 아니라면 const enum을 활용하는 것이 더 좋다는 생각입니다. 또한 문법적 편의성을 고려해 상수값은 enum으로, 불변 객체는 as const 로 관리하는게 편리한 것 같습니다. 타입스크립트가 존재하는 이유도 결론적으로 안정성 뿐만 아니라 DX 의 향상도 있다고 생각하여...
